# crnn
defaults:
  - audio: cqt
  - model: crnn
  - _self_

paths:
  cache_dir: ./cache
  checkpoint_dir: ./checkpoints
  checkpoint_path: null

train:
  batch_size: 16
  lr: 3e-4
  weight_decay: 1e-4
  epochs: 200
  patience: 15
  pos_weight: 4.0
  sequence_length: 1000
  num_workers: 8
  onset_weight: 1.5

wandb:
  project: amt-project
  entity: null
  name: null
